default:
  dnbr_path: "G:/Fire_Selectivity/NickPelletier - do not delete/dNBR rasters/"  # Path to folder containing DNBR .tif files (e.g., "/path/to/dnbr/")
  peatland_path: "E:/Jack/data/peatland_fire_selectivity/Peat_Canopy_2023_11_06.tif"      # Path to merged peatland-canopy raster file (e.g., "/path/to/landcover.tif")
  progression_path: "G:/Fire_Selectivity/NickPelletier - do not delete/fire polygons 2023/landscape_processed_polygons_km_oct18.shp"   # Path to fire progression shapefile (e.g., "/path/to/progression.shp")
  worker_log: "logs/worker_log.txt"  # Path to worker log file (e.g., "logs/worker_log.txt")
  error_log: "logs/error_log.txt"    # Path to error log file (e.g., "logs/error_log.txt")
  proj_dir: "!expr getwd()"  # Project directory set to current working directory
  processing_logs: "logs/fire_processing_logs/"  # Directory for processing logs (e.g., "logs/processing_logs/")
  used_available: "data/used_available_per_fire/"
  combined_output: "data/ua_fire_combined/"
  full_dataset_output: "data/full_dataset/"  # Directory for final combined dataset (e.g., "data/full_dataset/")


python:
  full_dataset_output: "data/full_dataset/"  # Directory for final combined dataset (e.g., "data/full_dataset/")
  lc_column: "Lc_class"        # or "lc_class"
  selectivity_output: "data/new_processed_progressions/selectivity_results/"  # Directory for selectivity results (e.g., "data/selectivity_results/")
  fwi_input: "data/FWI_metrics_2023_fires_all_dates_by_progression_Oct17KM_NEWclipped.csv"
  progression: "data/fire_progression_polygons/landscape_processed_polygons_km_oct18.shp"  
  progression_2: "data/progression_NBAC_km_oct2024/"
  dnbr_rasters: "data/dNBR rasters/"
  peatland_raster: "../../data/nickp_products/Peat_Canopy_2023_11_06.tif"
  progression_2_output: "data/progression_NBAC_km_oct2024/progression_NBAC_km_oct2024_jag.shp"
  new_ua_processed: "data/new_processed_progressions/used_available/"
  new_ua_consolidated: "data/new_processed_progressions/used_available_combined/"
  cluster_areas: "data/new_processed_progressions/cluster_areas/progression_landscape_areas_by_cluster.parquet"
  burned_areas: "data/new_processed_progressions/cluster_areas/burned_areas.parquet"
  by_cluster_ids: "data/new_processed_progressions/ua_clusterid/"
  ratios_output: "data/new_processed_progressions/ua_clusterid_ratios/"
  
